// build.cjs — bundles the ES modules used by the content script into ONE
// plain (non-module) script, so Chrome never has to do a runtime dynamic
// import() chain. This removes the class of bug where a chained import()
// fetch on a heavy SPA (TradingView) intermittently returns a broken/partial
// module and throws "SyntaxError: Unexpected end of input".
//
// Run: node build.cjs

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');

// Dependency order matters only for ONE reason in this codebase:
// sidebar.js executes `export const SidebarInstance = new Sidebar();`
// immediately at load time, and the Sidebar constructor touches Utils.
// Everything else is object literals / class defs whose methods aren't
// invoked until later, so as long as sidebar.js is last (before content.js)
// we're safe even with the Injector <-> Sidebar circular reference.
const FILES_IN_ORDER = [
  'constants.js',
  'logger.js',
  'utils.js',
  'store.js',
  'scanner.js',
  'journal-sync.js',
  'services/supabase.js',
  'services/upstox.js',
  'injector.js',
  'components/settings.js',
  'components/watchlist.js',
  'components/feedback.js',
  'sidebar.js',
  'tv-toolbar.js',
  'content.js',
];

function stripModuleSyntax(code, filename) {
  // Remove `import { ... } from '...';` (handles multi-line import lists too)
  code = code.replace(/^\s*import\s*\{[^}]*\}\s*from\s*['"][^'"]+['"];?\s*$/gm, '');
  code = code.replace(/^\s*import\s+[^\n;]+;\s*$/gm, '');

  // Turn `export const X = ...` / `export class X` / `export function X`
  // into plain declarations. Also handle `export default`.
  code = code.replace(/^export\s+default\s+/gm, '');
  code = code.replace(/^export\s+/gm, '');

  return `\n// ───── ${filename} ─────\n${code}\n`;
}

let bundle = `/**
 * TM Watchlist — bundled content script (auto-generated by build.cjs)
 * Do NOT edit directly — edit files in src/ and re-run "node build.cjs".
 * This file intentionally contains NO import()/import statements so Chrome
 * loads it as one plain classic script — no dynamic-import race conditions.
 */
(function () {
  'use strict';
`;

for (const rel of FILES_IN_ORDER) {
  const full = path.join(SRC, rel);
  const raw = fs.readFileSync(full, 'utf8');
  bundle += stripModuleSyntax(raw, rel);
}

bundle += `\n})();\n`;

const outPath = path.join(SRC, 'bundle.js');
fs.writeFileSync(outPath, bundle, 'utf8');
console.log(`Wrote ${outPath} (${bundle.length} bytes)`);
